# Generated by Django 3.2.7 on 2023-01-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20230123_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('director', models.CharField(max_length=30, verbose_name='Director')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('budget', models.IntegerField(verbose_name='Budget')),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
