# Generated by Django 3.2.7 on 2023-01-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
