# Generated by Django 3.2.7 on 2023-01-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20230126_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
